name: objectbox_benchmark
description: Simple ObjectBox-Dart performance benchmark
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  objectbox: any
  benchmark_harness: any

dev_dependencies:
  objectbox_generator: any
  build_runner: any

dependency_overrides:
  objectbox:
    path: ../objectbox
  objectbox_generator:
    path: ../generator
