name: objectbox_generator
version: 0.11.1
repository: https://github.com/objectbox/objectbox-dart
homepage: https://objectbox.io
description: ObjectBox binding code generator - finds annotated entities and adds them to the ObjectBox DB model.

environment:
  # min SDK v2.10.0 (or Flutter v1.22) - there were breaking changes in the analyzer/resolver
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  objectbox: 0.11.1
  build: ^1.0.0
  source_gen: ^0.9.0
  analyzer: ">=0.35.0 <0.100.0"
  glob: ^1.1.0
  path: ^1.6.0
  dart_style: ^1.3.0

# NOTE: remove before publishing
dependency_overrides:
  objectbox:
    path: ../objectbox