name: objectbox_test
version: 0.2.0
description: >-
  A simple tester for the ObjectBox Dart binding.
environment:
  sdk: '>=2.2.2 <3.0.0'
dependencies:
  objectbox:
    path: ../objectbox
dev_dependencies:
  build_runner: 1.0.0
  objectbox_model_generator:
    path: ../objectbox_model_generator
