name: objectbox
version: 0.3.0
description: >-
  ObjectBox binding for Dart.
environment:
  sdk: '>=2.5.0-dev.2.0 <3.0.0'
dependencies:
  flat_buffers: ^1.11.0
  utf: ^0.9.0
dev_dependencies:
  build_runner: 1.0.0
  objectbox_model_generator:
    path: bin/objectbox_model_generator
  test: ^1.0.0
