include: package:pedantic/analysis_options.yaml

linter:
  rules:
    # additional rules used by pub.dev
    non_constant_identifier_names: true

# exclude standalone packages:
analyzer:
  exclude:
    - example/**
    - generator/**
    - benchmark/**
    - test/objectbox.g.dart # TODO remove exception after #168 is implemented
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false