include: package:pedantic/analysis_options.yaml
# Effective dart has some things we don't use so let's stick with pedantic for now
# include: package:effective_dart/analysis_options.yaml

linter:
  # Some additional rules from pub.dev analyzer and package:effective_dart
  rules:
    - non_constant_identifier_names
    - constant_identifier_names
    - public_member_api_docs
    - prefer_expression_function_bodies
    - prefer_typing_uninitialized_variables
    - use_function_type_syntax_for_parameters
    - directives_ordering
    - avoid_positional_boolean_parameters
    - avoid_returning_this
    - unnecessary_brace_in_string_interps
    - unnecessary_lambdas
    - prefer_relative_imports
    - type_annotate_public_apis
    - prefer_initializing_formals
    # - lines_longer_than_80_chars

# exclude standalone packages:
analyzer:
  exclude:
    - example/**
    - generator/**
    - benchmark/**
    - lib/src/modelinfo/enums.dart
    - lib/src/native/bindings/objectbox-c.dart
    - lib/flatbuffers/** # Not really our code
    - test/objectbox.g.dart # TODO remove exception after #168 is implemented
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false