include: package:lints/recommended.yaml
# https://dart.dev/guides/language/analysis-options
# https://github.com/dart-lang/lints/blob/main/lib/core.yaml
# https://github.com/dart-lang/lints/blob/main/lib/recommended.yaml

linter:
  # Some additional rules from pub.dev analyzer and package:effective_dart
  rules:
    - avoid_positional_boolean_parameters
    - avoid_returning_this
    - directives_ordering
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_expression_function_bodies
    - prefer_relative_imports
    - public_member_api_docs
    - type_annotate_public_apis
    - unnecessary_lambdas

# exclude standalone packages:
analyzer:
  errors:
    public_member_api_docs: error
    type_annotate_public_apis: error
  # Note: pana ignores these exclude rules, better add ignore_for_file comments.
  exclude:
    - example/**
    - generator/**
    - benchmark/**
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false