name: objectbox_flutter_libs
version: 0.6.4
repository: https://github.com/objectbox/objectbox-dart
homepage: https://objectbox.io
description: ObjectBox is a super-fast NoSQL ACID compliant object database. This package contains flutter runtime libraries for ObjectBox.

environment:
  sdk: ">=2.6.0 <3.0.0"

flutter:
  plugin:
    android:
      package: io.objectbox.flutter.objectbox
      pluginClass: ObjectBoxFlutterPlugin
    ios:
      pluginClass: ObjectBoxFlutterPlugin
