name: Build and test

on: [ push, pull_request ]

defaults:
  run:
    shell: bash

jobs:
  generator:
    runs-on: ubuntu-20.04
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install ObjectBox C-API
        run: ./install.sh
      - name: Test
        run: ./generator/test.sh

  # make sure the init script doesn't stop working - it's not something we usually run during normal development
  init-script:
    runs-on: ubuntu-20.04
    steps:
      - uses: subosito/flutter-action@v1
      - uses: actions/checkout@v1
      - run: ./tool/init.sh

  lib:
    strategy:
      matrix:
        os:
          - windows-2019
          - macos-10.15
          - ubuntu-20.04
        dart:
          - latest  # currently same as the lowest supported
          - 2.12.0  # currently the lowest fully supported version (i.e. generator + lib)
    runs-on: ${{ matrix.os }}
    steps:
      - uses: cedx/setup-dart@v2
        with:
          version: ${{ matrix.dart }}
      - run: dart --version
      - uses: actions/checkout@v2
      - name: Install ObjectBox C-API
        working-directory: objectbox
        run: ../install.sh
      - name: Test
        working-directory: objectbox
        run: |
          ../tool/pub.sh get
          ../tool/pub.sh run build_runner build
          ../tool/pub.sh run test

  valgrind:
    runs-on: ubuntu-20.04
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install ObjectBox C-API
        run: ./install.sh
      - name: Install Valgrind
        run: |
          apt update
          apt install -y valgrind
      - name: Test
        working-directory: objectbox
        run: |
          ../tool/pub.sh get
          ../tool/pub.sh run build_runner build
          ./tool/valgrind.sh

  flutter-integration-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - macos-10.15
          - ubuntu-20.04
        channel:
          - beta
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}
      - run: echo $PATH
      - run: flutter --version
      - uses: actions/checkout@v2
      - run: make integration-test
        working-directory: objectbox