name: Build and test

on: [ push, pull_request ]

defaults:
  run:
    shell: bash

jobs:
  generator:
    runs-on: ubuntu-20.04
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install ObjectBox C-API
        run: ./install.sh
      - name: Run tests
        run: ./generator/test.sh

  lib:
    runs-on: ubuntu-20.04
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install ObjectBox C-API
        run: ./install.sh
      - run: pub get
      - name: Generate ObjectBox models
        run: pub run build_runner build
      - name: Run tests
        run: pub run test

  valgrind:
    runs-on: ubuntu-20.04
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install ObjectBox C-API
        run: ./install.sh
      - run: pub get
      - name: Generate ObjectBox models
        run: pub run build_runner build
      - name: Install Valgrind
        run: |
          apt update
          apt install -y valgrind
      - run: ./tool/valgrind.sh