name: Code analysis

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/dart-package-analyzer@v3
        id: analysis # set an id for the current step
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: objectbox

      # You can then use this id to retrieve the outputs in the next steps.
      # The following step shows how to exit the workflow with an error if a score is below 100:
      - name: Check scores
        shell: bash
        run: |
          if [[ "${{ steps.analysis.outputs.total }}" != "110" ]]; then
            echo "Expected score 110, got ${{ steps.analysis.outputs.total }}, please check the analysis report and resolve the issues"
            exit 1
          fi